# Generated by Django 4.2.2 on 2023-06-29 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('plan', models.CharField(choices=[('Arcade', 'Arcade'), ('Pro', 'Pro'), ('Advanced', 'Advanced')], max_length=200)),
                ('yearly', models.CharField(choices=[('on', 'yearly'), ('off', 'monthly')], max_length=200)),
                ('addons', models.CharField(choices=[('Larger Storage', 'Larger Storage'), ('Online Storage', 'Online Storage'), ('Customizable Profile', 'Customizable Profile')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
