# Generated by Django 4.2.2 on 2023-07-03 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0002_subscriptionplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multi_step_form.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=500),
        ),
    ]
