# Generated by Django 4.2.2 on 2023-07-03 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0003_alter_subscriptionplan_user_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='addons',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='addons',
            field=models.ManyToManyField(blank=True, to='multi_step_form.addon'),
        ),
    ]
