# Generated by Django 4.2.2 on 2023-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0006_alter_addon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
