# Generated by Django 4.2.2 on 2023-07-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0008_alter_addon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multi_step_form.user'),
        ),
    ]
