# Generated by Django 4.2.2 on 2023-07-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0009_alter_subscriptionplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='name',
        ),
        migrations.AddField(
            model_name='addon',
            name='Customizable_Profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addon',
            name='Larger_Storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addon',
            name='Online_Storage',
            field=models.BooleanField(default=False),
        ),
    ]
