# Generated by Django 4.2.2 on 2023-07-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0010_remove_addon_name_addon_customizable_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='addons',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='Customizable_Profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='Larger_Storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='Online_Storage',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AddOn',
        ),
    ]
