# Generated by Django 4.2.2 on 2023-07-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0011_remove_subscriptionplan_addons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='Customizable_Profile',
            field=models.BooleanField(default='off'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='Larger_Storage',
            field=models.BooleanField(default='off'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='Online_Storage',
            field=models.BooleanField(default='on'),
        ),
    ]
