# Generated by Django 4.2.2 on 2023-07-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0013_alter_subscriptionplan_customizable_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='Online_Storage',
            new_name='Online_storage',
        ),
    ]
