# Generated by Django 4.2.2 on 2023-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0014_rename_online_storage_subscriptionplan_online_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='Customizable_Profile',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='Larger_Storage',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='Online_storage',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=200),
        ),
    ]
