# Generated by Django 4.2.2 on 2023-07-04 21:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0015_alter_subscriptionplan_customizable_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Plan_Total', models.IntegerField(blank=True)),
                ('Larger_Storage_Total', models.IntegerField(blank=True)),
                ('Online_storage_Total', models.IntegerField(blank=True)),
                ('Customizable_Profile_Total', models.IntegerField(blank=True)),
                ('BillTotal', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multi_step_form.subscriptionplan')),
            ],
        ),
    ]
