# Generated by Django 4.2.2 on 2023-07-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0016_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='Online_storage_Total',
            new_name='Online_service_Total',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='Online_storage',
            new_name='Online_service',
        ),
    ]
