# Generated by Django 4.2.2 on 2023-07-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_step_form', '0017_rename_online_storage_total_bill_online_service_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='Customizable_Profile',
            new_name='Customizable_profile',
        ),
    ]
